default: &default
  adapter: postgresql
  encoding: unicode
  username: pramod
  password: password
  host: localhost
  pool: 5

development:
  <<: *default
  database: blogs_app_development

production:
  <<: *default
  database: blogs_app_production